import * as model from '../models/user.model';
import { type usersTable } from '@/drizzle/schemas/users';

export const usersService = {
	async createUser(user: typeof usersTable.$inferInsert) {
		if (!user) {
			throw new Error('User not provided');
		}
		if (!user.kinde_id) {
			throw new Error('Kinde ID not provided');
		}
		// id is auto-generated by the database, so we don't need to provide it
		const data: typeof usersTable.$inferInsert = {
			kinde_id: user.kinde_id,
			username: user.username,
			email: user.email,
			first_name: user.first_name,
			last_name: user.last_name,
			date_of_birth: user.date_of_birth,
			country: user.country,
			is_password_reset_requested: user.is_password_reset_requested,
			is_suspended: user.is_suspended,
			user_since: user.user_since,
			last_login: user.last_login,
			login_count: user.login_count,
			created_at: user.created_at,
		};
		// Only include id if explicitly provided
		if (user.id) {
			data.id = user.id;
		}
		const result = await model.usersModel.create(data);
		// Return the created user from the insert result
		return result[0];
	},
	async update(
		userId: string,
		userData: Partial<typeof usersTable.$inferInsert>,
	) {
		const result = await model.usersModel.update(userId, userData);
		// Return the updated user from the update result
		if (result.length === 0) {
			throw new Error('User not found');
		}
		return result[0];
	},
	async getAll() {
		const users = await model.usersModel.getAll();
		return users;
	},
	async getByKindeId(kindeId: string) {
		const users = await model.usersModel.getByKindeId(kindeId);
		if (users.length === 0) {
			throw new Error('User not found');
		}
		return users[0];
	},
	async getByUsername(username: string) {
		const users = await model.usersModel.getByUsername(username);
		if (users.length === 0) {
			throw new Error('User not found');
		}
		return users[0];
	},
	async getByEmail(email: string) {
		const users = await model.usersModel.getByEmail(email);
		if (users.length === 0) {
			throw new Error('User not found');
		}
		return users[0];
	},
	async getById(id: string) {
		const users = await model.usersModel.getById(id);
		if (users.length === 0) {
			throw new Error('User not found');
		}
		return users[0];
	},
};
